import Link from "next/link";

// import "./globals.css";

export const metadata = {
  title: "test-not-found",
  description: "Generated by appncy",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">test-not-found</Link>
        </header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} test-not-found
        </footer>
      </body>
    </html>
  );
}
